package com.example.ui.dashboard

enum class AppLanguage(val code: String, val displayName: String) {
    ES("es", "Castellano"),
    CA("ca", "Valencià")
}

data class Translation(
    val tabInicio: String,
    val tabMapa: String,
    val tabBus: String,
    val tabMetro: String,
    val tabCercanias: String,
    val tabAjustes: String,

    val headerMetroTitle: String,
    val headerMetroSubtitle: String,
    val headerBusTitle: String,
    val headerBusSubtitle: String,
    val headerCercaniasTitle: String,
    val headerCercaniasSubtitle: String,
    val headerAjustesTitle: String,
    val headerAjustesSubtitle: String,

    val settingLanguageTitle: String,
    val settingGpsPermissionTitle: String,
    val settingGpsPermissionSubtitle: String,
    val settingGpsPermissionAction: String,
    val settingThemeTitle: String,
    val settingMetroStationsTitle: String,
    val settingCercaniasStationsTitle: String,
    val settingStationsSelectedSuffix: String,
    val settingGoogleCalendarTitle: String,
    val settingGoogleCalendarSubtitle: String,
    val settingGoogleCalendarConnected: String,
    val settingGoogleCalendarDisconnect: String,
    val settingGoogleCalendarConnect: String,
    val settingAboutTitle: String,
    val settingAboutSubtitle: String,

    val aboutTitle: String,
    val aboutSubtitle: String,
    val aboutDevTitle: String,
    val aboutDevBody: String,
    val aboutDisclaimerTitle: String,
    val aboutDisclaimerBody: String,
    val aboutSourcesTitle: String,
    val aboutSourcesBody: String,
    val aboutExemptionTitle: String,
    val aboutExemptionItems: List<Pair<String, String>>,
    val aboutPrivacyTitle: String,
    val aboutPrivacyItems: List<Pair<String, String>>,
    val aboutLicensesTitle: String,
    val aboutLicensesBody: String,
    val aboutUnderstood: String,
    val searchPlaceholder: String,

    val favoritesTitle: String,
    val noAvisos: String,
    val noAvisosRed: String,
    val noAvisosRedDesc: String,
    val noAvisosRedCercaniasDesc: String,
    val noAccessibilityAvisos: String,
    val noAccessibilityAvisosDesc: String,
    val noTweetsAvailable: String,
    val updatedLabel: String,
    val publishedLabel: String,
    val accessibilityAndLifts: String,
    val activeAvisosLabel: String,
    
    val noCardsSaved: String,
    val cardsSavedDesc: String,
    val addCardLabel: String,
    val addCardInstruction: String,
    val cardNumberLabel: String,
    val cardNumberPlaceholder: String,
    val customNameLabel: String,
    val customNamePlaceholder: String,
    val cardNumberDigitsError: String,
    val addBtn: String,
    val cancelBtn: String,
    val acceptBtn: String,
    val alertTitle: String,
    val cardDetailTitle: String,
    val editNameBtnDesc: String,
    val saveBtnDesc: String,
    val deleteCardBtnDesc: String,
    val markAsInactiveLabel: String,
    val markAsInactiveDesc: String,
    val detailInfoLabel: String,
    val transportTitleLabel: String,
    val cardClassLabel: String,
    val extensionLabel: String,
    val expiryDateLabel: String,
    val lastTopupLabel: String,
    val remainingBalanceLabel: String,
    val remainingTripsLabel: String,
    val operatorLabel: String,
    val validityZonesLabel: String,
    val unlimitedTripsValue: String,
    val historyNotAvailableDesc: String,
    val historyLabel: String,
    val closeBtn: String,
    val saveAndCloseBtn: String,
    val deleteCardConfirmTitle: String,
    val deleteCardConfirmDesc: String,
    val deleteBtn: String,
    val notAvailableValue: String,
    val editNameAssignedLabel: String,

    val selectMetroStationLabel: String,
    val addMetroFavDesc: String,
    val searchStopPlaceholder: String,
    val clearSearchDesc: String,
    val noStopsActive: String,
    val noFavStopsSaved: String,
    val noStopsWithinRadius: String,
    val noStopsNearMetro: String,
    val nextBusesLabel: String,
    val noArrivalEstimates: String,
    val immediateValue: String,
    val calendarTitle: String,
    val eventsLabel: String,
    val noEventsToday: String,
    val viewOnMapsDesc: String,
    val liveIndicatorDesc: String,
    val searchLabel: String,

    val queryingWeatherForecast: String,
    val maxTempLabel: String,
    val minTempLabel: String,
    val rainLabel: String,
    
    val searchLabelPlural: String,
    val searchStationLabel: String,
    val queryingLiveDepartures: String,
    val noLiveDepartures: String,
    val noLiveDeparturesDesc: String
)

object AppTexts {
    private val castellano = Translation(
        tabInicio = "Inicio",
        tabMapa = "Mapa",
        tabBus = "Bus",
        tabMetro = "Metro",
        tabCercanias = "Cercanías",
        tabAjustes = "Ajustes",

        headerMetroTitle = "Metrovalencia",
        headerMetroSubtitle = "Próximos trenes en tiempo real y estado de la red",
        headerBusTitle = "Buses y bicicletas",
        headerBusSubtitle = "Horarios y paradas de autobuses en tiempo real",
        headerCercaniasTitle = "Cercanías Renfe",
        headerCercaniasSubtitle = "Próximas salidas y avisos de la red de Valencia",
        headerAjustesTitle = "Ajustes",
        headerAjustesSubtitle = "Configura tus preferencias de la aplicación",

        settingLanguageTitle = "Idioma",
        settingGpsPermissionTitle = "Permisos de ubicación",
        settingGpsPermissionSubtitle = "Permite consultar clima y estaciones más cercanas",
        settingGpsPermissionAction = "Activar",
        settingThemeTitle = "Modo oscuro",
        settingMetroStationsTitle = "Estaciones de Metrovalencia",
        settingCercaniasStationsTitle = "Estaciones de Cercanías",
        settingStationsSelectedSuffix = "estaciones seleccionadas",
        settingGoogleCalendarTitle = "Calendario del dispositivo",
        settingGoogleCalendarSubtitle = "Sincroniza los eventos del calendario local del dispositivo",
        settingGoogleCalendarConnected = "✓ Sincronizado con el calendario",
        settingGoogleCalendarDisconnect = "Desconectar calendario",
        settingGoogleCalendarConnect = "Conectar con calendario",
        settingAboutTitle = "Acerca de la app",
        settingAboutSubtitle = "Autoría, fuentes de datos, exención de responsabilidad y privacidad",

        aboutTitle = "Acerca de esta app",
        aboutSubtitle = "Información legal y fuentes de datos",
        aboutDevTitle = "Desarrollo y Autoría",
        aboutDevBody = "Esta aplicación ha sido creada y desarrollada de forma independiente.",
        aboutDisclaimerTitle = "Desvinculación Oficial y Marcas",
        aboutDisclaimerBody = "Aviso importante: Esta aplicación es un proyecto independiente de desarrollo de software. NO existe ningún tipo de vinculación, afiliación, patrocinio, asociación comercial ni respaldo oficial con:\n\n• Renfe Operadora (Cercanías Renfe)\n• Ferrocarrils de la Generalitat Valenciana (FGV / Metrovalencia)\n• Empresa Municipal de Transportes de València (EMT València) ni el Ajuntament de València\n• Valenbisi / JCDecaux España\n• Autoritat de Transport Metropolità de València (ATMV / Título SUMA)\n\nTodos los nombres comerciales, logotipos, marcas registradas y denominaciones de líneas, estaciones, paradas o tarifas pertenecen de forma exclusiva a sus respectivos titulares.",
        aboutSourcesTitle = "Fuentes de Datos, APIs y Atribución",
        aboutSourcesBody = "Esta aplicación funciona gracias a la reutilización de datos abiertos procedentes de plataformas oficiales e iniciativas comunitarias. Se reconoce y agradece expresamente la labor de los siguientes proveedores y proyectos:",
        aboutExemptionTitle = "Exención de Responsabilidad y Datos Offline",
        aboutExemptionItems = listOf(
            "Carácter orientativo" to "La información sobre horarios programados, itinerarios y estimaciones en tiempo real se ofrece «tal cual» (as is) con fines puramente informativos. La precisión de los tiempos de llegada y avisos depende de la disponibilidad y actualización de las APIs públicas de origen.",
            "Horarios teóricos locales" to "Los horarios programados offline proceden de la última base de datos integrada en la aplicación. Pueden sufrir variaciones imprevistas por festividades, eventos especiales u obras en la red.",
            "Conexión a red" to "El acceso a la información en tiempo real, mapas y estado de los servicios requiere conexión activa a Internet.",
            "Limitación de responsabilidad" to "No se garantiza la ausencia absoluta de errores, variaciones imprevistas o fallos de conexión en los servidores externos de datos. Quien ha desarrollado esta aplicación no se hace responsable de las consecuencias derivadas de transportes o transbordos perdidos, cambios imprevistos de vía/andén, retrasos no reflejados o decisiones tomadas a partir de la información mostrada."
        ),
        aboutPrivacyTitle = "Privacidad y Tratamiento de Datos",
        aboutPrivacyItems = listOf(
            "Sin registro de datos personales" to "Esta aplicación no recopila, no almacena ni comparte ningún tipo de dato personal con servidores externos ni terceros.",
            "Geolocalización" to "El acceso a la ubicación del dispositivo se utiliza de manera exclusivamente local, instantánea y anónima para ordenar y mostrar las estaciones o paradas más cercanas. Las coordenadas no se guardan ni se rastrean en ningún historial.",
            "Almacenamiento local" to "Las preferencias configuradas dentro de la app (como las estaciones guardadas en favoritos o la elección del tema visual) se almacenan únicamente de forma privada dentro de tu propio dispositivo."
        ),
        aboutLicensesTitle = "Licencias",
        aboutLicensesBody = "Esta aplicación hace uso de librerías y componentes de código abierto bajo sus correspondientes licencias de software libre (Apache 2.0 / MIT).",
        aboutUnderstood = "Entendido",
        searchPlaceholder = "Buscar y añadir estaciones favoritas...",

        favoritesTitle = "Mis estaciones favoritas",
        noAvisos = "Sin avisos",
        noAvisosRed = "Red sin incidencias",
        noAvisosRedDesc = "Todas las líneas de Metrovalencia están operando con normalidad.",
        noAvisosRedCercaniasDesc = "Todas las líneas de Cercanías Renfe de Valencia operan con normalidad.",
        noAccessibilityAvisos = "Accesibilidad sin incidencias",
        noAccessibilityAvisosDesc = "No se han detectado problemas en escaleras mecánicas o ascensores.",
        noTweetsAvailable = "No hay tweets de incidencias disponibles.",
        updatedLabel = "Actualizado: ",
        publishedLabel = "Publicado: ",
        accessibilityAndLifts = "ACCESIBILIDAD Y ASCENSORES",
        activeAvisosLabel = "Avisos activos",
        
        noCardsSaved = "No tienes tarjetas guardadas",
        cardsSavedDesc = "Añade tus tarjetas de Metrovalencia / SUMA para consultar tus viajes, saldo o renovación cómodamente.",
        addCardLabel = "Añadir Tarjeta",
        addCardInstruction = "Introduce el número de 12 dígitos en el reverso de la tarjeta",
        cardNumberLabel = "Número de tarjeta *",
        cardNumberPlaceholder = "Ej: 234567890123 o 1234567890",
        customNameLabel = "Nombre personalizado (opcional)",
        customNamePlaceholder = "Ej: Mi Móbilis, Trabajo, SUMA",
        cardNumberDigitsError = "El número debe tener exactamente 10 o 12 dígitos",
        addBtn = "Añadir",
        cancelBtn = "Cancelar",
        acceptBtn = "Aceptar",
        alertTitle = "Aviso",
        cardDetailTitle = "Detalle de Tarjeta",
        editNameBtnDesc = "Editar nombre",
        saveBtnDesc = "Guardar",
        deleteCardBtnDesc = "Borrar tarjeta",
        markAsInactiveLabel = "Marcar como inactiva/caducada",
        markAsInactiveDesc = "Fuerza el estado a inactiva si los datos de la API no son precisos",
        detailInfoLabel = "Información detallada",
        transportTitleLabel = "Título de transporte",
        cardClassLabel = "Clase de tarjeta",
        extensionLabel = "Ampliación",
        expiryDateLabel = "Fecha de caducidad",
        lastTopupLabel = "Última recarga",
        remainingBalanceLabel = "Saldo restante",
        remainingTripsLabel = "Viajes restantes",
        operatorLabel = "Operador",
        validityZonesLabel = "Zonas de validez",
        unlimitedTripsValue = "Viajes ilimitados",
        historyNotAvailableDesc = "Historial de trayectos no disponible para este tipo de tarjeta",
        historyLabel = "Historial de trayectos",
        closeBtn = "Cerrar",
        saveAndCloseBtn = "Guardar y cerrar",
        deleteCardConfirmTitle = "¿Borrar Tarjeta?",
        deleteCardConfirmDesc = "¿Estás seguro de que deseas eliminar esta tarjeta de transporte de tu lista?",
        deleteBtn = "Eliminar",
        notAvailableValue = "No disponible",
        editNameAssignedLabel = "Editar nombre asignado",

        selectMetroStationLabel = "Selecciona estación de metro:",
        addMetroFavDesc = "Añade estaciones de metro favoritas para usar este filtro.",
        searchStopPlaceholder = "Buscar parada",
        clearSearchDesc = "Limpiar",
        noStopsActive = "No se encontraron paradas activas",
        noFavStopsSaved = "No tienes paradas de autobús favoritas guardadas",
        noStopsWithinRadius = "No se encontraron paradas en un radio de 500m",
        noStopsNearMetro = "No se encontraron paradas cerca de la estación seleccionada",
        nextBusesLabel = "PRÓXIMOS AUTOBUSES",
        noArrivalEstimates = "No hay estimaciones de llegada disponibles.",
        immediateValue = "Inmediato",
        calendarTitle = "Calendario",
        eventsLabel = "Eventos",
        noEventsToday = "No hay eventos hoy",
        viewOnMapsDesc = "Ver en Google Maps",
        liveIndicatorDesc = "En Vivo",
        searchLabel = "Buscar",

        queryingWeatherForecast = "Consultando previsión en directo...",
        maxTempLabel = "Máx",
        minTempLabel = "Mín",
        rainLabel = "Lluvia",
        
        searchLabelPlural = "Buscar...",
        searchStationLabel = "Buscar estación...",
        queryingLiveDepartures = "Consultando previsión en directo...",
        noLiveDepartures = "Sin previsiones en directo",
        noLiveDeparturesDesc = "No existen previsiones de trenes en directo en este momento para la estación seleccionada."
    )

    private val valenciano = Translation(
        tabInicio = "Inici",
        tabMapa = "Mapa",
        tabBus = "Bus",
        tabMetro = "Metro",
        tabCercanias = "Rodalia",
        tabAjustes = "Ajustos",

        headerMetroTitle = "Metrovalencia",
        headerMetroSubtitle = "Pròxims trens en temps real i estat de la xarxa",
        headerBusTitle = "Buses y bicicletas",
        headerBusSubtitle = "Horaris i parades d'autobusos en temps real",
        headerCercaniasTitle = "Rodalia Renfe",
        headerCercaniasSubtitle = "Pròximes eixides i avisos de la xarxa de València",
        headerAjustesTitle = "Ajustos",
        headerAjustesSubtitle = "Configura les teues preferències de l'aplicació",

        settingLanguageTitle = "Idioma",
        settingGpsPermissionTitle = "Permisos d'ubicació",
        settingGpsPermissionSubtitle = "Permet consultar clima i estacions més properes",
        settingGpsPermissionAction = "Activar",
        settingThemeTitle = "Mode fosc",
        settingMetroStationsTitle = "Estacions de Metrovalencia",
        settingCercaniasStationsTitle = "Estacions de Rodalia",
        settingStationsSelectedSuffix = "estacions seleccionades",
        settingGoogleCalendarTitle = "Calendari del dispositiu",
        settingGoogleCalendarSubtitle = "Sincronitza els esdeveniments del calendari local del dispositiu",
        settingGoogleCalendarConnected = "✓ Sincronitzat amb el calendari",
        settingGoogleCalendarDisconnect = "Desconnectar calendari",
        settingGoogleCalendarConnect = "Connectar amb calendari",
        settingAboutTitle = "Quant a l'app",
        settingAboutSubtitle = "Autoria, fonts de dades, exempció de responsabilitat i privacitat",

        aboutTitle = "Quant a aquesta app",
        aboutSubtitle = "Informació legal i fonts de dades",
        aboutDevTitle = "Desenvolupament i Autoria",
        aboutDevBody = "Aquesta aplicació ha sigut creada i desenvolupada de forma independent.",
        aboutDisclaimerTitle = "Desvinculació Oficial i Marques",
        aboutDisclaimerBody = "Avís important: Aquesta aplicació és un projecte independent de desenvolupament de programari. NO existeix cap tipus de vinculació, afiliació, patrocini, associació comercial ni suport oficial amb:\n\n• Renfe Operadora (Rodalia Renfe)\n• Ferrocarrils de la Generalitat Valenciana (FGV / Metrovalencia)\n• Empresa Municipal de Transports de València (EMT València) ni l'Ajuntament de València\n• Valenbisi / JCDecaux España\n• Autoritat de Transport Metropolità de València (ATMV / Títol SUMA)\n\nTots els noms comercials, logotips, marques registrades i denominacions de línies, estacions, parades o tarifes pertanyen de forma exclusiva als seus respectius titulars.",
        aboutSourcesTitle = "Fonts de Dades, APIs i Atribució",
        aboutSourcesBody = "Aquesta aplicació funciona gràcies a la reutilització de dades obertes procedents de plataformes oficials i iniciatives comunitàries. Es reconeix i agraeix expressament la tasca dels següents proveïdors i projectes:",
        aboutExemptionTitle = "Exempció de Responsabilitat i Dades Offline",
        aboutExemptionItems = listOf(
            "Caràcter orientatiu" to "La informació sobre horaris programats, itineraris i estimacions en temps real s'ofereix «tal qual» (as is) amb fins purament informatius. La precisió dels temps d'arribada i avisos depén de la disponibilitat i actualització de les APIs públiques d'origen.",
            "Horaris teòrics locals" to "Els horaris programats offline procedeixen de la darrera base de dades integrada en l'aplicació. Poden patir variacions imprevistes per festivitats, esdeveniments especials o obres a la xarxa.",
            "Connexió a xarxa" to "L'accés a la informació en temps real, mapes i estat dels serveis requereix connexió activa a Internet.",
            "Limitació de responsabilitat" to "No es garanteix l'absència absoluta d'errors, variacions imprevistes o fallades de connexió en els servidors externs de dades. Qui ha desenvolupat aquesta aplicació no es fa responsable de les conseqüències d'haver perdut transports o transbords, canvis imprevistos de via/andana, retards no reflectits o decisions preses a partir de la informació mostrada."
        ),
        aboutPrivacyTitle = "Privacitat i Tractament de Dades",
        aboutPrivacyItems = listOf(
            "Sense registre de dades personals" to "Aquesta aplicació no recopila, no emmagatzema ni comparteix cap tipus de dada personal amb servidors externs ni tercers.",
            "Geolocalització" to "L'accés a la ubicació del dispositiu s'utilitza de manera exclusivament local, instantània i anònima per a ordenar i mostrar les estacions o parades més properes. Les coordenades no es guarden ni es rastregen en cap historial.",
            "Emmagatzematge local" to "Les preferències configurades dins de l'app (com les estacions guardades en favorits o l'elecció de l'aspecte o tema visual) s'emmagatzemen únicament de forma privada dins del teu propi dispositiu."
        ),
        aboutLicensesTitle = "Llicències",
        aboutLicensesBody = "Aquesta aplicació fa ús de llibreries i components de codi obert sota les seues corresponents llicències de programari lliure (Apache 2.0 / MIT).",
        aboutUnderstood = "Entés",
        searchPlaceholder = "Cercar i afegir estacions favorites...",

        favoritesTitle = "Les meues estacions favorites",
        noAvisos = "Sense avisos",
        noAvisosRed = "Xarxa sense incidències",
        noAvisosRedDesc = "Totes les línies de Metrovalencia estan operant amb normalitat.",
        noAvisosRedCercaniasDesc = "Totes les línies de Rodalia Renfe de València operen amb normalitat.",
        noAccessibilityAvisos = "Accessibilitat sense incidències",
        noAccessibilityAvisosDesc = "No s'han detectat problemes en escales mecàniques o ascensors.",
        noTweetsAvailable = "No hi ha tweets d'incidències disponibles.",
        updatedLabel = "Actualitzat: ",
        publishedLabel = "Publicat: ",
        accessibilityAndLifts = "ACCESSIBILITAT I ASCENSORS",
        activeAvisosLabel = "Avisos actius",
        
        noCardsSaved = "No tens targetes guardades",
        cardsSavedDesc = "Afig les teues targetes de Metrovalencia / SUMA per a consultar els teus viatges, saldo o renovació còmodament.",
        addCardLabel = "Afegir targeta",
        addCardInstruction = "Introdueix el número de 12 dígits al revers de la targeta",
        cardNumberLabel = "Número de targeta *",
        cardNumberPlaceholder = "Ex: 234567890123 o 1234567890",
        customNameLabel = "Nom personalitzat (opcional)",
        customNamePlaceholder = "Ex: El meu Móbilis, Treball, SUMA",
        cardNumberDigitsError = "El número ha de tindre exactament 10 o 12 dígits",
        addBtn = "Afegir",
        cancelBtn = "Cancel·lar",
        acceptBtn = "Acceptar",
        alertTitle = "Avís",
        cardDetailTitle = "Detall de la Targeta",
        editNameBtnDesc = "Editar nom",
        saveBtnDesc = "Guardar",
        deleteCardBtnDesc = "Borrar targeta",
        markAsInactiveLabel = "Marcar com a inactiva/caducada",
        markAsInactiveDesc = "Força l'estat a inactiva si les dades de l'API no són precises",
        detailInfoLabel = "Informació detallada",
        transportTitleLabel = "Títol de transport",
        cardClassLabel = "Classe de targeta",
        extensionLabel = "Ampliació",
        expiryDateLabel = "Data de caducitat",
        lastTopupLabel = "Última recàrrega",
        remainingBalanceLabel = "Saldo restant",
        remainingTripsLabel = "Viatges restants",
        operatorLabel = "Operador",
        validityZonesLabel = "Zones de validesa",
        unlimitedTripsValue = "Viatges il·limitats",
        historyNotAvailableDesc = "Historial de trajectes no disponible per a aquest tipus de targeta",
        historyLabel = "Historial de trajectes",
        closeBtn = "Tancar",
        saveAndCloseBtn = "Guardar i tancar",
        deleteCardConfirmTitle = "Esborrar targeta?",
        deleteCardConfirmDesc = "Estàs segur que vols eliminar aquesta targeta de transport de la teua llista?",
        deleteBtn = "Eliminar",
        notAvailableValue = "No disponible",
        editNameAssignedLabel = "Editar nom assignat",

        selectMetroStationLabel = "Selecciona estació de metro:",
        addMetroFavDesc = "Afig estacions de metro favorites per a utilitzar aquest filtre.",
        searchStopPlaceholder = "Cercar parada",
        clearSearchDesc = "Netejar",
        noStopsActive = "No s'han trobat parades actives",
        noFavStopsSaved = "No tens parades d'autobús favorites guardades",
        noStopsWithinRadius = "No s'han trobat parades en un radi de 500m",
        noStopsNearMetro = "No s'han trobat parades prop de l'estació seleccionada",
        nextBusesLabel = "PRÒXIMS AUTOBUSOS",
        noArrivalEstimates = "No hi ha estimacions d'arribada disponibles.",
        immediateValue = "Inmediat",
        calendarTitle = "Calendari",
        eventsLabel = "Esdeveniments",
        noEventsToday = "No hi ha esdeveniments hui",
        viewOnMapsDesc = "Veure en Google Maps",
        liveIndicatorDesc = "En Directe",
        searchLabel = "Cercar",

        queryingWeatherForecast = "Consultant previsió en directe...",
        maxTempLabel = "Màx",
        minTempLabel = "Mín",
        rainLabel = "Pluja",
        
        searchLabelPlural = "Cercar...",
        searchStationLabel = "Cercar estació...",
        queryingLiveDepartures = "Consultant previsió en directe...",
        noLiveDepartures = "Sense previsions en directe",
        noLiveDeparturesDesc = "No hi ha previsions de trens en directe en aquest moment per a l'estació seleccionada."
    )

    fun get(language: AppLanguage): Translation {
        return when (language) {
            AppLanguage.ES -> castellano
            AppLanguage.CA -> valenciano
        }
    }
}
